<?php
declare(strict_types=1);

/**
 * Shared Project Vacancies dataset.
 * Vacancy statuses:
 * - 'draft' -> Draft (Belum diajukan)
 * - 'review' -> Menunggu Verifikasi (Verifikasi Admin)
 * - 'revision' -> Perlu Revisi (Catatan perbaikan dari Admin)
 * - 'rejected' -> Ditolak (Tidak disetujui Admin)
 * - 'active' -> Tayang Aktif (Sudah disetujui & dipublikasikan)
 */
function gig_project_vacancies(): array
{
    return [
        [
            'id' => 'GIG-2026-09-001',
            'title' => 'Redesign UI/UX Dashboard Prototype KarirHub',
            'category' => 'Desain & Kreatif',
            'status' => 'active',
            'statusLabel' => 'Tayang Aktif',
            'budget' => 'Rp 8.500.000',
            'duration' => '3 Minggu',
            'applicantsCount' => 2,
            'acceptedCount' => 1,
            'quota' => 1,
            'location' => 'Remote / Indonesia',
            'posted' => '01 Sep 2026',
            'skills' => ['Figma', 'UI/UX', 'Design System', 'Prototyping'],
            'desc' => 'Dibutuhkan UI/UX designer berpengalaman untuk merancang prototype interaktif dashboard KarirHub dengan tampilan modern.',
            'deadline' => '20 Sep 2026',
            'adminNote' => 'Lowongan telah diverifikasi dan disetujui oleh Admin KarirHub pada 01 Sep 2026.',
            'employer' => 'PT ABC',
        ],
        [
            'id' => 'GIG-2026-09-002',
            'title' => 'Integrasi REST API Modul Notifikasi SMS & WhatsApp',
            'category' => 'IT & Pemrograman',
            'status' => 'active',
            'statusLabel' => 'Tayang Aktif',
            'budget' => 'Rp 6.000.000',
            'duration' => '2 Minggu',
            'applicantsCount' => 2,
            'acceptedCount' => 1,
            'quota' => 1,
            'location' => 'Remote / Bandung',
            'posted' => '03 Sep 2026',
            'skills' => ['PHP', 'REST API', 'Webhook', 'MySQL'],
            'desc' => 'Mengembangkan endpoint webhook dan mengintegrasikan provider SMS/WA ke core sistem.',
            'deadline' => '18 Sep 2026',
            'adminNote' => 'Lowongan disetujui Admin pada 03 Sep 2026.',
            'employer' => 'PT ABC',
        ],
        [
            'id' => 'GIG-2026-09-003',
            'title' => 'Kampanye Media Sosial & Copywriting Peluncuran Fitur',
            'category' => 'Pemasaran & Konten',
            'status' => 'review',
            'statusLabel' => 'Menunggu Verifikasi',
            'budget' => 'Rp 4.500.000',
            'duration' => '1 Bulan',
            'applicantsCount' => 2,
            'acceptedCount' => 0,
            'quota' => 1,
            'location' => 'Remote / Surabaya',
            'posted' => '07 Sep 2026',
            'skills' => ['Copywriting', 'Social Media', 'Content Plan'],
            'desc' => 'Menyusun strategi konten peluncuran fitur Gig Worker untuk meningkatkan awareness.',
            'deadline' => '28 Sep 2026',
            'adminNote' => 'Permohonan lowongan dalam antrean verifikasi Admin. Estimasi waktu 1x24 jam.',
        ],
        [
            'id' => 'GIG-2026-09-004',
            'title' => 'Audit Aksesibilitas WCAG 2.1 Dashboard Internal',
            'category' => 'Desain & Kreatif',
            'status' => 'revision',
            'statusLabel' => 'Perlu Revisi',
            'budget' => 'Rp 3.500.000',
            'duration' => '2 Minggu',
            'applicantsCount' => 0,  // not active — cannot have applicants
            'acceptedCount' => 0,
            'quota' => 1,
            'location' => 'Remote / Jakarta',
            'posted' => '08 Sep 2026',
            'skills' => ['Figma', 'WCAG', 'UI Audit'],
            'desc' => 'Audit aksesibilitas standar WCAG 2.1 AA untuk komponen dashboard internal perusahaan.',
            'deadline' => '30 Sep 2026',
            'adminNote' => 'Revisi dari Admin: Harap perjelas cakupan rincian kriteria pengujian aksesibilitas dan format laporan yang diharapkan.',
        ],
        [
            'id' => 'GIG-2026-09-005',
            'title' => 'Scraping Data Produk Tanpa Izin Legal',
            'category' => 'IT & Pemrograman',
            'status' => 'rejected',
            'statusLabel' => 'Ditolak',
            'budget' => 'Rp 2.000.000',
            'duration' => '1 Minggu',
            'applicantsCount' => 0,
            'acceptedCount' => 0,
            'quota' => 1,
            'location' => 'Remote',
            'posted' => '05 Sep 2026',
            'skills' => ['Python', 'Web Scraping'],
            'desc' => 'Melakukan pengumpulan data massal dari platform eksternal.',
            'deadline' => '15 Sep 2026',
            'adminNote' => 'Penolakan dari Admin: Lowongan tidak memenuhi Syarat & Ketentuan KarirHub terkait perlindungan data pribadi dan hak cipta.',
        ],
        [
            'id' => 'GIG-2026-09-006',
            'title' => 'Penyusunan Modul Pelatihan Internal Gig Worker',
            'category' => 'Pemasaran & Konten',
            'status' => 'draft',
            'statusLabel' => 'Draft',
            'budget' => 'Rp 5.000.000',
            'duration' => '3 Minggu',
            'applicantsCount' => 0,
            'acceptedCount' => 0,
            'quota' => 1,
            'location' => 'Remote / Jakarta',
            'posted' => '09 Sep 2026',
            'skills' => ['Technical Writing', 'Instructional Design'],
            'desc' => 'Draft materi pelatihan onboarding mitra freelancer baru.',
            'deadline' => '05 Okt 2026',
            'adminNote' => 'Draft lowongan belum dikirim ke Admin.',
        ],
        [
            'id' => 'GIG-2026-09-007',
            'title' => 'Pengembangan Aplikasi Mobile E-Commerce (React Native)',
            'category' => 'IT & Pemrograman',
            'status' => 'active',
            'statusLabel' => 'Tayang Aktif',
            'budget' => 'Rp 12.000.000',
            'duration' => '1 Bulan',
            'applicantsCount' => 3,
            'acceptedCount' => 0,
            'quota' => 1,
            'location' => 'Remote / Jakarta',
            'posted' => '10 Sep 2026',
            'skills' => ['React Native', 'Mobile App', 'REST API', 'Redux'],
            'desc' => 'Membangun antarmuka mobile e-commerce responsif untuk iOS dan Android lengkap dengan integrasi payment gateway dan katalog produk.',
            'deadline' => '10 Okt 2026',
            'adminNote' => 'Disetujui Admin KarirHub pada 10 Sep 2026.',
            'employer' => 'PT Talenta Digital Indonesia',
            'deliverables' => 'Source code React Native, dokumentasi build APK/IPA, dan panduan integrasi API.',
        ],
        [
            'id' => 'GIG-2026-09-008',
            'title' => 'Desain Visual Asset & Branding Kit UMKM Go Digital',
            'category' => 'Desain & Kreatif',
            'status' => 'active',
            'statusLabel' => 'Tayang Aktif',
            'budget' => 'Rp 5.500.000',
            'duration' => '2 Minggu',
            'applicantsCount' => 4,
            'acceptedCount' => 1,
            'quota' => 2,
            'location' => 'Remote / Yogyakarta',
            'posted' => '12 Sep 2026',
            'skills' => ['Figma', 'Illustrator', 'Branding', 'Logo Design'],
            'desc' => 'Pembuatan logo vector, pilihan tipografi, palette warna, serta 15 template postingan Instagram untuk UMKM kuliner.',
            'deadline' => '26 Sep 2026',
            'adminNote' => 'Disetujui Admin pada 12 Sep 2026.',
            'employer' => 'CV Kreasi Visual Nusantara',
            'deliverables' => 'File vector logo (.AI/.SVG), brand guidelines PDF, dan template Canva/Figma.',
        ],
        [
            'id' => 'GIG-2026-09-009',
            'title' => 'Penyusunan Copywriting Website & Landing Page SaaS',
            'category' => 'Pemasaran & Konten',
            'status' => 'active',
            'statusLabel' => 'Tayang Aktif',
            'budget' => 'Rp 4.000.000',
            'duration' => '10 Hari',
            'applicantsCount' => 1,
            'acceptedCount' => 0,
            'quota' => 1,
            'location' => 'Remote / Bandung',
            'posted' => '14 Sep 2026',
            'skills' => ['Copywriting', 'SEO Writing', 'Landing Page', 'Value Proposition'],
            'desc' => 'Penulisan naskah landing page yang persuasif untuk produk SaaS B2B, mencakup value proposition, FAQ, dan call to action.',
            'deadline' => '24 Sep 2026',
            'adminNote' => 'Disetujui Admin pada 14 Sep 2026.',
            'employer' => 'PT Solusi Awan Indonesia',
            'deliverables' => 'Dokumen copy landing page (Google Docs/PDF) dan peta kata kunci SEO.',
        ],
        [
            'id' => 'GIG-2026-09-010',
            'title' => 'Pembersihan & Pengolahan Data Transaksi Penjualan (Data Cleaning)',
            'category' => 'Data Analytics & Entry',
            'status' => 'active',
            'statusLabel' => 'Tayang Aktif',
            'budget' => 'Rp 3.500.000',
            'duration' => '1 Minggu',
            'applicantsCount' => 2,
            'acceptedCount' => 0,
            'quota' => 1,
            'location' => 'Remote / Semarang',
            'posted' => '15 Sep 2026',
            'skills' => ['Excel / Spreadsheet', 'Python Data Processing', 'Data Cleaning'],
            'desc' => 'Pembersihan dan standarisasi 50.000+ baris data transaksi penjualan toko online untuk analisis laporan triwulan.',
            'deadline' => '22 Sep 2026',
            'adminNote' => 'Disetujui Admin pada 15 Sep 2026.',
            'employer' => 'PT Analytics Indonesia Jaya',
            'deliverables' => 'Dataset tersaring (.CSV/.XLSX) dan ringkasan metode validasi data.',
        ],
        [
            'id' => 'GIG-2026-09-011',
            'title' => 'Optimasi SEO Organik & Audit Kata Kunci Portal Berita',
            'category' => 'Pemasaran & Konten',
            'status' => 'active',
            'statusLabel' => 'Tayang Aktif',
            'budget' => 'Rp 6.500.000',
            'duration' => '3 Minggu',
            'applicantsCount' => 3,
            'acceptedCount' => 0,
            'quota' => 1,
            'location' => 'Remote / Jakarta',
            'posted' => '16 Sep 2026',
            'skills' => ['SEO On-Page', 'Google Analytics', 'Ahrefs', 'Keyword Research'],
            'desc' => 'Audit teknis SEO on-page, riset kata kunci potensial, dan panduan optimasi struktur URL serta meta deskripsi.',
            'deadline' => '07 Okt 2026',
            'adminNote' => 'Disetujui Admin pada 16 Sep 2026.',
            'employer' => 'PT Media Informasi Terpadu',
            'deliverables' => 'Laporan audit teknis SEO, spreadsheet kata kunci, dan panduan redaksi konten.',
        ],
        [
            'id' => 'GIG-2026-09-012',
            'title' => 'Pengembangan Backend Microservices & API Gateway (Node.js)',
            'category' => 'IT & Pemrograman',
            'status' => 'active',
            'statusLabel' => 'Tayang Aktif',
            'budget' => 'Rp 15.000.000',
            'duration' => '1.5 Bulan',
            'applicantsCount' => 5,
            'acceptedCount' => 0,
            'quota' => 1,
            'location' => 'Remote / Indonesia',
            'posted' => '18 Sep 2026',
            'skills' => ['Node.js', 'Express', 'Docker', 'Redis', 'PostgreSQL'],
            'desc' => 'Refactoring arsitektur backend monolith menjadi microservices modular berbasis Docker dan Redis cache.',
            'deadline' => '30 Okt 2026',
            'adminNote' => 'Disetujui Admin pada 18 Sep 2026.',
            'employer' => 'PT Infrastruktur Cloud Utama',
            'deliverables' => 'Repository backend, Docker compose file, dan spesifikasi OpenAPI 3.0.',
        ],
        [
            'id' => 'GIG-2026-09-013',
            'title' => 'Penyuntingan & Audio Mastering Video Edukasi Karir',
            'category' => 'Desain & Kreatif',
            'status' => 'active',
            'statusLabel' => 'Tayang Aktif',
            'budget' => 'Rp 7.000.000',
            'duration' => '2 Minggu',
            'applicantsCount' => 2,
            'acceptedCount' => 0,
            'quota' => 1,
            'location' => 'Remote / Surabaya',
            'posted' => '19 Sep 2026',
            'skills' => ['Premiere Pro', 'After Effects', 'Video Editing', 'Motion Graphics'],
            'desc' => 'Editing 10 video modul pembelajaran daring (durasi @ 10-15 menit) lengkap dengan teks subtitel dan motion graphics.',
            'deadline' => '03 Okt 2026',
            'adminNote' => 'Disetujui Admin pada 19 Sep 2026.',
            'employer' => 'Yayasan Edukasi Bangsa',
            'deliverables' => '10 File MP4 Render 1080p60 dan file proyek Premiere Pro.',
        ],
    ];
}

function gig_find_vacancy(string $id): ?array
{
    $vacancies = gig_project_vacancies();
    $cleanId = strtolower(trim($id));
    foreach ($vacancies as $v) {
        if (strtolower($v['id']) === $cleanId || strtolower(str_replace('gig-2026-09-', '', strtolower($v['id']))) === $cleanId) {
            return $v;
        }
    }
    return null;
}
