<?php
declare(strict_types=1);

function gig_project_vacancies(): array
{
    return [
        [
            'id' => 'GIG-2026-09-004',
            'title' => 'Audit Aksesibilitas Dashboard Internal',
            'category' => 'Desain & Kreatif',
            'status' => 'draft',
            'statusLabel' => 'Draft',
            'budget' => 'Rp 3.500.000',
            'duration' => '2 Minggu',
            'applicantsCount' => 0,
            'acceptedCount' => 0,
            'quota' => 1,
            'location' => 'Remote / Jakarta',
            'posted' => '09 Sep 2026',
            'skills' => ['Figma', 'WCAG', 'UI Audit'],
            'desc' => 'Draft audit aksesibilitas untuk dashboard internal perusahaan.',
            'deadline' => '30 Sep 2026',
        ],
        [
            'id' => 'GIG-2026-09-001',
            'title' => 'Redesign UI/UX Dashboard Prototype KarirHub',
            'category' => 'Desain & Kreatif',
            'status' => 'active',
            'statusLabel' => 'Tayang Aktif',
            'budget' => 'Rp 8.500.000',
            'duration' => '3 Minggu',
            'applicantsCount' => 2,
            'acceptedCount' => 1,
            'quota' => 1,
            'location' => 'Remote / Indonesia',
            'posted' => '01 Sep 2026',
            'skills' => ['Figma', 'UI/UX', 'Design System', 'Prototyping'],
            'desc' => 'Dibutuhkan UI/UX designer berpengalaman untuk merancang prototype interaktif dashboard KarirHub.',
            'deadline' => '20 Sep 2026',
        ],
        [
            'id' => 'GIG-2026-09-002',
            'title' => 'Integrasi REST API Modul Notifikasi SMS & WhatsApp',
            'category' => 'IT & Pemrograman',
            'status' => 'active',
            'statusLabel' => 'Tayang Aktif',
            'budget' => 'Rp 6.000.000',
            'duration' => '2 Minggu',
            'applicantsCount' => 2,
            'acceptedCount' => 1,
            'quota' => 1,
            'location' => 'Remote / Bandung',
            'posted' => '03 Sep 2026',
            'skills' => ['PHP', 'REST API', 'Webhook', 'MySQL'],
            'desc' => 'Mengembangkan endpoint webhook dan mengintegrasikan provider SMS/WA ke core sistem.',
            'deadline' => '18 Sep 2026',
        ],
        [
            'id' => 'GIG-2026-09-003',
            'title' => 'Kampanye Media Sosial & Copywriting Peluncuran Fitur',
            'category' => 'Pemasaran & Konten',
            'status' => 'review',
            'statusLabel' => 'Menunggu Verifikasi',
            'budget' => 'Rp 4.500.000',
            'duration' => '1 Bulan',
            'applicantsCount' => 2,
            'acceptedCount' => 0,
            'quota' => 1,
            'location' => 'Remote / Surabaya',
            'posted' => '07 Sep 2026',
            'skills' => ['Copywriting', 'Social Media', 'Content Plan'],
            'desc' => 'Menyusun strategi konten peluncuran fitur Gig Worker.',
            'deadline' => '28 Sep 2026',
        ],
    ];
}
